export const UI = {
  SET_SPLASH_INDEX: 'UI.SET_SPLASH_INDEX',
  SET_HERO_INDEX: 'UI.SET_HERO_INDEX',
  SET_NAVIGATION_OPEN: 'UI.SET_NAVIGATION_OPEN',
  SET_INITIAL_RENDER_STATUS: 'UI.SET_INITIAL_RENDER_STATUS'
}